### ISSUE TITLE
Bootstrap skin problem

### ISSUE THREAD

**Issue by gtbu** [mahotilo/CKE_Themes#1]
Bootstrap skin has white background in the settings and dark background in the site

This gives the icons a white background :
.cke_button, span.cke_combo_text, span.cke_combo_inlinelabel {background-color:white !important;}

**Comment by mahotilo** [comment]
Updated. Try now. 
It is not easy to revert all our changes in inline_edit.css

**Comment by gtbu** [comment]
It functions - and i made a similar patch in the inlinedit.css in the CE-version -great (I hesitate to install phpmailer 6 and csstidy ... unwanted fork....)

**Comment by mahotilo** [comment]
Glad to hear. 
I'll be looking for a more elegant solution to the problem and maybe ask for some changes to inline_edit.css and Moono-Lisa theme editor.css in TS.
Because at the moment all the dark themes are broken

**Comment by gtbu** [comment]
A notice to Josh announcement of  Twig : https://github.com/bolt/bolt has such[ an implementation ](https://bolt.cm/feature/twig)- and is also flat - just the installation and the administration.....

**Comment by mahotilo** [comment]
New version should solve this problem for all themes.

UPD
or this newest one :)

**Comment by mahotilo** [comment]
Now the Bootstrap theme in TS looks exactly as contrast as in the author's demo.

![image](https://user-images.githubusercontent.com/14929385/72218439-572efe80-3543-11ea-9acc-36ffaea2701b.png)
